// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: local.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GatewayStakingMode int32

const (
	GatewayStakingMode_dataonly GatewayStakingMode = 0
	GatewayStakingMode_full     GatewayStakingMode = 1
	GatewayStakingMode_light    GatewayStakingMode = 2
)

// Enum value maps for GatewayStakingMode.
var (
	GatewayStakingMode_name = map[int32]string{
		0: "dataonly",
		1: "full",
		2: "light",
	}
	GatewayStakingMode_value = map[string]int32{
		"dataonly": 0,
		"full":     1,
		"light":    2,
	}
)

func (x GatewayStakingMode) Enum() *GatewayStakingMode {
	p := new(GatewayStakingMode)
	*p = x
	return p
}

func (x GatewayStakingMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GatewayStakingMode) Descriptor() protoreflect.EnumDescriptor {
	return file_local_proto_enumTypes[0].Descriptor()
}

func (GatewayStakingMode) Type() protoreflect.EnumType {
	return &file_local_proto_enumTypes[0]
}

func (x GatewayStakingMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GatewayStakingMode.Descriptor instead.
func (GatewayStakingMode) EnumDescriptor() ([]byte, []int) {
	return file_local_proto_rawDescGZIP(), []int{0}
}

type PubkeyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address           []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	OnboardingAddress []byte `protobuf:"bytes,2,opt,name=onboarding_address,json=onboardingAddress,proto3" json:"onboarding_address,omitempty"`
}

func (x *PubkeyRes) Reset() {
	*x = PubkeyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubkeyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubkeyRes) ProtoMessage() {}

func (x *PubkeyRes) ProtoReflect() protoreflect.Message {
	mi := &file_local_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubkeyRes.ProtoReflect.Descriptor instead.
func (*PubkeyRes) Descriptor() ([]byte, []int) {
	return file_local_proto_rawDescGZIP(), []int{0}
}

func (x *PubkeyRes) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *PubkeyRes) GetOnboardingAddress() []byte {
	if x != nil {
		return x.OnboardingAddress
	}
	return nil
}

type PubkeyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PubkeyReq) Reset() {
	*x = PubkeyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubkeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubkeyReq) ProtoMessage() {}

func (x *PubkeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_local_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubkeyReq.ProtoReflect.Descriptor instead.
func (*PubkeyReq) Descriptor() ([]byte, []int) {
	return file_local_proto_rawDescGZIP(), []int{1}
}

type SignReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SignReq) Reset() {
	*x = SignReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignReq) ProtoMessage() {}

func (x *SignReq) ProtoReflect() protoreflect.Message {
	mi := &file_local_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignReq.ProtoReflect.Descriptor instead.
func (*SignReq) Descriptor() ([]byte, []int) {
	return file_local_proto_rawDescGZIP(), []int{2}
}

func (x *SignReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SignRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *SignRes) Reset() {
	*x = SignRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRes) ProtoMessage() {}

func (x *SignRes) ProtoReflect() protoreflect.Message {
	mi := &file_local_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRes.ProtoReflect.Descriptor instead.
func (*SignRes) Descriptor() ([]byte, []int) {
	return file_local_proto_rawDescGZIP(), []int{3}
}

func (x *SignRes) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type EcdhReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *EcdhReq) Reset() {
	*x = EcdhReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EcdhReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EcdhReq) ProtoMessage() {}

func (x *EcdhReq) ProtoReflect() protoreflect.Message {
	mi := &file_local_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EcdhReq.ProtoReflect.Descriptor instead.
func (*EcdhReq) Descriptor() ([]byte, []int) {
	return file_local_proto_rawDescGZIP(), []int{4}
}

func (x *EcdhReq) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

type EcdhRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Secret []byte `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
}

func (x *EcdhRes) Reset() {
	*x = EcdhRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EcdhRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EcdhRes) ProtoMessage() {}

func (x *EcdhRes) ProtoReflect() protoreflect.Message {
	mi := &file_local_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EcdhRes.ProtoReflect.Descriptor instead.
func (*EcdhRes) Descriptor() ([]byte, []int) {
	return file_local_proto_rawDescGZIP(), []int{5}
}

func (x *EcdhRes) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

type ConfigReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *ConfigReq) Reset() {
	*x = ConfigReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigReq) ProtoMessage() {}

func (x *ConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_local_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigReq.ProtoReflect.Descriptor instead.
func (*ConfigReq) Descriptor() ([]byte, []int) {
	return file_local_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigReq) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type ConfigRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*ConfigValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *ConfigRes) Reset() {
	*x = ConfigRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRes) ProtoMessage() {}

func (x *ConfigRes) ProtoReflect() protoreflect.Message {
	mi := &file_local_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRes.ProtoReflect.Descriptor instead.
func (*ConfigRes) Descriptor() ([]byte, []int) {
	return file_local_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigRes) GetValues() []*ConfigValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type ConfigValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ConfigValue) Reset() {
	*x = ConfigValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigValue) ProtoMessage() {}

func (x *ConfigValue) ProtoReflect() protoreflect.Message {
	mi := &file_local_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigValue.ProtoReflect.Descriptor instead.
func (*ConfigValue) Descriptor() ([]byte, []int) {
	return file_local_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigValue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigValue) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConfigValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type KeyedUri struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Uri     string `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
}

func (x *KeyedUri) Reset() {
	*x = KeyedUri{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyedUri) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyedUri) ProtoMessage() {}

func (x *KeyedUri) ProtoReflect() protoreflect.Message {
	mi := &file_local_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyedUri.ProtoReflect.Descriptor instead.
func (*KeyedUri) Descriptor() ([]byte, []int) {
	return file_local_proto_rawDescGZIP(), []int{9}
}

func (x *KeyedUri) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *KeyedUri) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type HeightReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HeightReq) Reset() {
	*x = HeightReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeightReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeightReq) ProtoMessage() {}

func (x *HeightReq) ProtoReflect() protoreflect.Message {
	mi := &file_local_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeightReq.ProtoReflect.Descriptor instead.
func (*HeightReq) Descriptor() ([]byte, []int) {
	return file_local_proto_rawDescGZIP(), []int{10}
}

type HeightRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height         uint64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	BlockAge       uint64    `protobuf:"varint,2,opt,name=block_age,json=blockAge,proto3" json:"block_age,omitempty"`
	Gateway        *KeyedUri `protobuf:"bytes,3,opt,name=gateway,proto3" json:"gateway,omitempty"`
	GatewayVersion *uint64   `protobuf:"varint,4,opt,name=gateway_version,json=gatewayVersion,proto3,oneof" json:"gateway_version,omitempty"`
}

func (x *HeightRes) Reset() {
	*x = HeightRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeightRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeightRes) ProtoMessage() {}

func (x *HeightRes) ProtoReflect() protoreflect.Message {
	mi := &file_local_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeightRes.ProtoReflect.Descriptor instead.
func (*HeightRes) Descriptor() ([]byte, []int) {
	return file_local_proto_rawDescGZIP(), []int{11}
}

func (x *HeightRes) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *HeightRes) GetBlockAge() uint64 {
	if x != nil {
		return x.BlockAge
	}
	return 0
}

func (x *HeightRes) GetGateway() *KeyedUri {
	if x != nil {
		return x.Gateway
	}
	return nil
}

func (x *HeightRes) GetGatewayVersion() uint64 {
	if x != nil && x.GatewayVersion != nil {
		return *x.GatewayVersion
	}
	return 0
}

type RegionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegionReq) Reset() {
	*x = RegionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionReq) ProtoMessage() {}

func (x *RegionReq) ProtoReflect() protoreflect.Message {
	mi := &file_local_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionReq.ProtoReflect.Descriptor instead.
func (*RegionReq) Descriptor() ([]byte, []int) {
	return file_local_proto_rawDescGZIP(), []int{12}
}

type RegionRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Region int32 `protobuf:"varint,1,opt,name=region,proto3" json:"region,omitempty"`
}

func (x *RegionRes) Reset() {
	*x = RegionRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionRes) ProtoMessage() {}

func (x *RegionRes) ProtoReflect() protoreflect.Message {
	mi := &file_local_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionRes.ProtoReflect.Descriptor instead.
func (*RegionRes) Descriptor() ([]byte, []int) {
	return file_local_proto_rawDescGZIP(), []int{13}
}

func (x *RegionRes) GetRegion() int32 {
	if x != nil {
		return x.Region
	}
	return 0
}

type AddGatewayReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner       []byte             `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Payer       []byte             `protobuf:"bytes,2,opt,name=payer,proto3" json:"payer,omitempty"`
	StakingMode GatewayStakingMode `protobuf:"varint,3,opt,name=staking_mode,json=stakingMode,proto3,enum=helium.local.GatewayStakingMode" json:"staking_mode,omitempty"`
}

func (x *AddGatewayReq) Reset() {
	*x = AddGatewayReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGatewayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGatewayReq) ProtoMessage() {}

func (x *AddGatewayReq) ProtoReflect() protoreflect.Message {
	mi := &file_local_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGatewayReq.ProtoReflect.Descriptor instead.
func (*AddGatewayReq) Descriptor() ([]byte, []int) {
	return file_local_proto_rawDescGZIP(), []int{14}
}

func (x *AddGatewayReq) GetOwner() []byte {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *AddGatewayReq) GetPayer() []byte {
	if x != nil {
		return x.Payer
	}
	return nil
}

func (x *AddGatewayReq) GetStakingMode() GatewayStakingMode {
	if x != nil {
		return x.StakingMode
	}
	return GatewayStakingMode_dataonly
}

type AddGatewayRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddGatewayTxn []byte `protobuf:"bytes,1,opt,name=add_gateway_txn,json=addGatewayTxn,proto3" json:"add_gateway_txn,omitempty"`
}

func (x *AddGatewayRes) Reset() {
	*x = AddGatewayRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_local_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGatewayRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGatewayRes) ProtoMessage() {}

func (x *AddGatewayRes) ProtoReflect() protoreflect.Message {
	mi := &file_local_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGatewayRes.ProtoReflect.Descriptor instead.
func (*AddGatewayRes) Descriptor() ([]byte, []int) {
	return file_local_proto_rawDescGZIP(), []int{15}
}

func (x *AddGatewayRes) GetAddGatewayTxn() []byte {
	if x != nil {
		return x.AddGatewayTxn
	}
	return nil
}

var File_local_proto protoreflect.FileDescriptor

var file_local_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x68,
	0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x22, 0x55, 0x0a, 0x0a, 0x70,
	0x75, 0x62, 0x6b, 0x65, 0x79, 0x5f, 0x72, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x2d, 0x0a, 0x12, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x69, 0x6e,
	0x67, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x11, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x22, 0x0c, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x5f, 0x72, 0x65, 0x71,
	0x22, 0x1e, 0x0a, 0x08, 0x73, 0x69, 0x67, 0x6e, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x28, 0x0a, 0x08, 0x73, 0x69, 0x67, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x24, 0x0a, 0x08, 0x65, 0x63,
	0x64, 0x68, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x22, 0x22, 0x0a, 0x08, 0x65, 0x63, 0x64, 0x68, 0x5f, 0x72, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x73, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x22, 0x20, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x72,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x40, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x5f, 0x72, 0x65, 0x73, 0x12, 0x32, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x6c, 0x6f,
	0x63, 0x61, 0x6c, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x4c, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x37, 0x0a, 0x09, 0x6b, 0x65, 0x79, 0x65, 0x64, 0x5f,
	0x75, 0x72, 0x69, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x72, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x22,
	0x0c, 0x0a, 0x0a, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x22, 0xb6, 0x01,
	0x0a, 0x0a, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x68, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x41, 0x67,
	0x65, 0x12, 0x31, 0x0a, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x6c, 0x6f, 0x63, 0x61,
	0x6c, 0x2e, 0x6b, 0x65, 0x79, 0x65, 0x64, 0x5f, 0x75, 0x72, 0x69, 0x52, 0x07, 0x67, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x12, 0x2c, 0x0a, 0x0f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52,
	0x0e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x88,
	0x01, 0x01, 0x42, 0x12, 0x0a, 0x10, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x0c, 0x0a, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x5f, 0x72, 0x65, 0x71, 0x22, 0x24, 0x0a, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x5f, 0x72,
	0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x22, 0x84, 0x01, 0x0a, 0x0f, 0x61,
	0x64, 0x64, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x14,
	0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x79, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x05, 0x70, 0x61, 0x79, 0x65, 0x72, 0x12, 0x45, 0x0a, 0x0c, 0x73, 0x74,
	0x61, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x22, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x2e,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x73, 0x74, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x5f,
	0x6d, 0x6f, 0x64, 0x65, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x4d, 0x6f, 0x64,
	0x65, 0x22, 0x39, 0x0a, 0x0f, 0x61, 0x64, 0x64, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x5f, 0x72, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x61, 0x64, 0x64, 0x5f, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x5f, 0x74, 0x78, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x61,
	0x64, 0x64, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x54, 0x78, 0x6e, 0x2a, 0x39, 0x0a, 0x14,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x73, 0x74, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x5f,
	0x6d, 0x6f, 0x64, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x6f, 0x6e, 0x6c, 0x79,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x66, 0x75, 0x6c, 0x6c, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x10, 0x02, 0x32, 0xba, 0x03, 0x0a, 0x03, 0x61, 0x70, 0x69, 0x12,
	0x3c, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x18, 0x2e, 0x68, 0x65, 0x6c, 0x69,
	0x75, 0x6d, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x2e, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x5f,
	0x72, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x2e, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x5f, 0x72, 0x65, 0x73, 0x12, 0x36, 0x0a,
	0x04, 0x73, 0x69, 0x67, 0x6e, 0x12, 0x16, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x6c,
	0x6f, 0x63, 0x61, 0x6c, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x5f, 0x72, 0x65, 0x71, 0x1a, 0x16, 0x2e,
	0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x2e, 0x73, 0x69, 0x67,
	0x6e, 0x5f, 0x72, 0x65, 0x73, 0x12, 0x36, 0x0a, 0x04, 0x65, 0x63, 0x64, 0x68, 0x12, 0x16, 0x2e,
	0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x2e, 0x65, 0x63, 0x64,
	0x68, 0x5f, 0x72, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x6c,
	0x6f, 0x63, 0x61, 0x6c, 0x2e, 0x65, 0x63, 0x64, 0x68, 0x5f, 0x72, 0x65, 0x73, 0x12, 0x3c, 0x0a,
	0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x18, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d,
	0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x72, 0x65,
	0x71, 0x1a, 0x18, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c,
	0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x72, 0x65, 0x73, 0x12, 0x3c, 0x0a, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x18, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x6c,
	0x6f, 0x63, 0x61, 0x6c, 0x2e, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x1a,
	0x18, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x2e, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x12, 0x3c, 0x0a, 0x06, 0x72, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x12, 0x18, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x2e, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x71, 0x1a, 0x18, 0x2e,
	0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x2e, 0x72, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x12, 0x4b, 0x0a, 0x0b, 0x61, 0x64, 0x64, 0x5f, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12, 0x1d, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e,
	0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x2e, 0x61, 0x64, 0x64, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x5f, 0x72, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x6c,
	0x6f, 0x63, 0x61, 0x6c, 0x2e, 0x61, 0x64, 0x64, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x5f, 0x72, 0x65, 0x73, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_local_proto_rawDescOnce sync.Once
	file_local_proto_rawDescData = file_local_proto_rawDesc
)

func file_local_proto_rawDescGZIP() []byte {
	file_local_proto_rawDescOnce.Do(func() {
		file_local_proto_rawDescData = protoimpl.X.CompressGZIP(file_local_proto_rawDescData)
	})
	return file_local_proto_rawDescData
}

var file_local_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_local_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_local_proto_goTypes = []interface{}{
	(GatewayStakingMode)(0), // 0: helium.local.gateway_staking_mode
	(*PubkeyRes)(nil),       // 1: helium.local.pubkey_res
	(*PubkeyReq)(nil),       // 2: helium.local.pubkey_req
	(*SignReq)(nil),         // 3: helium.local.sign_req
	(*SignRes)(nil),         // 4: helium.local.sign_res
	(*EcdhReq)(nil),         // 5: helium.local.ecdh_req
	(*EcdhRes)(nil),         // 6: helium.local.ecdh_res
	(*ConfigReq)(nil),       // 7: helium.local.config_req
	(*ConfigRes)(nil),       // 8: helium.local.config_res
	(*ConfigValue)(nil),     // 9: helium.local.config_value
	(*KeyedUri)(nil),        // 10: helium.local.keyed_uri
	(*HeightReq)(nil),       // 11: helium.local.height_req
	(*HeightRes)(nil),       // 12: helium.local.height_res
	(*RegionReq)(nil),       // 13: helium.local.region_req
	(*RegionRes)(nil),       // 14: helium.local.region_res
	(*AddGatewayReq)(nil),   // 15: helium.local.add_gateway_req
	(*AddGatewayRes)(nil),   // 16: helium.local.add_gateway_res
}
var file_local_proto_depIdxs = []int32{
	9,  // 0: helium.local.config_res.values:type_name -> helium.local.config_value
	10, // 1: helium.local.height_res.gateway:type_name -> helium.local.keyed_uri
	0,  // 2: helium.local.add_gateway_req.staking_mode:type_name -> helium.local.gateway_staking_mode
	2,  // 3: helium.local.api.pubkey:input_type -> helium.local.pubkey_req
	3,  // 4: helium.local.api.sign:input_type -> helium.local.sign_req
	5,  // 5: helium.local.api.ecdh:input_type -> helium.local.ecdh_req
	7,  // 6: helium.local.api.config:input_type -> helium.local.config_req
	11, // 7: helium.local.api.height:input_type -> helium.local.height_req
	13, // 8: helium.local.api.region:input_type -> helium.local.region_req
	15, // 9: helium.local.api.add_gateway:input_type -> helium.local.add_gateway_req
	1,  // 10: helium.local.api.pubkey:output_type -> helium.local.pubkey_res
	4,  // 11: helium.local.api.sign:output_type -> helium.local.sign_res
	6,  // 12: helium.local.api.ecdh:output_type -> helium.local.ecdh_res
	8,  // 13: helium.local.api.config:output_type -> helium.local.config_res
	12, // 14: helium.local.api.height:output_type -> helium.local.height_res
	14, // 15: helium.local.api.region:output_type -> helium.local.region_res
	16, // 16: helium.local.api.add_gateway:output_type -> helium.local.add_gateway_res
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_local_proto_init() }
func file_local_proto_init() {
	if File_local_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_local_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubkeyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubkeyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EcdhReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EcdhRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyedUri); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeightReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeightRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGatewayReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_local_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGatewayRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_local_proto_msgTypes[11].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_local_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_local_proto_goTypes,
		DependencyIndexes: file_local_proto_depIdxs,
		EnumInfos:         file_local_proto_enumTypes,
		MessageInfos:      file_local_proto_msgTypes,
	}.Build()
	File_local_proto = out.File
	file_local_proto_rawDesc = nil
	file_local_proto_goTypes = nil
	file_local_proto_depIdxs = nil
}
