name: Main

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build web
        run: npm install && npm run release
        working-directory: ./web
      - name: Get version
        run: echo "::set-output name=version::${GITHUB_REF##*/}"
        id: version
      - name: Build
        env:
          version: ${{ steps.version.outputs.version }}
        run:  |
          GOOS=linux GOARCH=arm64 sh build.sh
          GOOS=linux GOARCH=amd64 sh build.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            hm-diag_linux_arm64.deb
            hm-diag_linux_arm64
            hm-diag_linux_amd64.deb
            hm-diag_linux_amd64